# Generated by Django 4.1.3 on 2022-11-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("convertible", "Convertible"),
                            ("hatch", "Hatch"),
                            ("sedan", "Sedan"),
                        ],
                        max_length=15,
                        verbose_name="Model",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("gray", "Gray"),
                            ("yellow", "Yellow"),
                        ],
                        max_length=15,
                        verbose_name="Model",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="person.person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["name"],
            },
        ),
    ]
